# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sim_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 731)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_Rom = QtWidgets.QVBoxLayout()
        self.verticalLayout_Rom.setObjectName("verticalLayout_Rom")
        self.romView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.romView.sizePolicy().hasHeightForWidth())
        self.romView.setSizePolicy(sizePolicy)
        self.romView.setObjectName("romView")
        self.verticalLayout_Rom.addWidget(self.romView)
        self.horizontalLayout.addLayout(self.verticalLayout_Rom)
        self.verticalLayout_Ram = QtWidgets.QVBoxLayout()
        self.verticalLayout_Ram.setObjectName("verticalLayout_Ram")
        self.ramView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.ramView.sizePolicy().hasHeightForWidth())
        self.ramView.setSizePolicy(sizePolicy)
        self.ramView.setObjectName("ramView")
        self.verticalLayout_Ram.addWidget(self.ramView)
        self.horizontalLayout.addLayout(self.verticalLayout_Ram)
        self.verticalLayout_Reg = QtWidgets.QVBoxLayout()
        self.verticalLayout_Reg.setObjectName("verticalLayout_Reg")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(-1, -1, -1, 0)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_Reg = QtWidgets.QLabel(self.centralwidget)
        self.label_Reg.setObjectName("label_Reg")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Reg)
        self.label_A = QtWidgets.QLabel(self.centralwidget)
        self.label_A.setObjectName("label_A")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_A)
        self.lineEdit_A = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_A.setEnabled(False)
        self.lineEdit_A.setObjectName("lineEdit_A")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_A)
        self.label_D = QtWidgets.QLabel(self.centralwidget)
        self.label_D.setObjectName("label_D")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_D)
        self.lineEdit_D = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_D.setEnabled(False)
        self.lineEdit_D.setObjectName("lineEdit_D")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_D)
        self.label_S = QtWidgets.QLabel(self.centralwidget)
        self.label_S.setObjectName("label_S")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_S)
        self.lineEdit_S = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_S.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_S.sizePolicy().hasHeightForWidth())
        self.lineEdit_S.setSizePolicy(sizePolicy)
        self.lineEdit_S.setObjectName("lineEdit_S")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_S)
        self.label_inM = QtWidgets.QLabel(self.centralwidget)
        self.label_inM.setObjectName("label_inM")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_inM)
        self.lineEdit_inM = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_inM.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_inM.sizePolicy().hasHeightForWidth())
        self.lineEdit_inM.setSizePolicy(sizePolicy)
        self.lineEdit_inM.setObjectName("lineEdit_inM")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_inM)
        self.label_outM = QtWidgets.QLabel(self.centralwidget)
        self.label_outM.setObjectName("label_outM")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_outM)
        self.lineEdit_outM = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_outM.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_outM.sizePolicy().hasHeightForWidth())
        self.lineEdit_outM.setSizePolicy(sizePolicy)
        self.lineEdit_outM.setObjectName("lineEdit_outM")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_outM)
        self.verticalLayout_Reg.addLayout(self.formLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LEDR9 = QtWidgets.QCheckBox(self.groupBox)
        self.LEDR9.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEDR9.sizePolicy().hasHeightForWidth())
        self.LEDR9.setSizePolicy(sizePolicy)
        self.LEDR9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LEDR9.setText("")
        self.LEDR9.setObjectName("LEDR9")
        self.horizontalLayout_3.addWidget(self.LEDR9)
        self.LEDR8 = QtWidgets.QCheckBox(self.groupBox)
        self.LEDR8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEDR8.sizePolicy().hasHeightForWidth())
        self.LEDR8.setSizePolicy(sizePolicy)
        self.LEDR8.setText("")
        self.LEDR8.setIconSize(QtCore.QSize(16, 16))
        self.LEDR8.setObjectName("LEDR8")
        self.horizontalLayout_3.addWidget(self.LEDR8)
        self.LEDR7 = QtWidgets.QCheckBox(self.groupBox)
        self.LEDR7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEDR7.sizePolicy().hasHeightForWidth())
        self.LEDR7.setSizePolicy(sizePolicy)
        self.LEDR7.setText("")
        self.LEDR7.setObjectName("LEDR7")
        self.horizontalLayout_3.addWidget(self.LEDR7)
        self.LEDR6 = QtWidgets.QCheckBox(self.groupBox)
        self.LEDR6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEDR6.sizePolicy().hasHeightForWidth())
        self.LEDR6.setSizePolicy(sizePolicy)
        self.LEDR6.setText("")
        self.LEDR6.setObjectName("LEDR6")
        self.horizontalLayout_3.addWidget(self.LEDR6)
        self.LEDR5 = QtWidgets.QCheckBox(self.groupBox)
        self.LEDR5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEDR5.sizePolicy().hasHeightForWidth())
        self.LEDR5.setSizePolicy(sizePolicy)
        self.LEDR5.setText("")
        self.LEDR5.setObjectName("LEDR5")
        self.horizontalLayout_3.addWidget(self.LEDR5)
        self.LEDR4 = QtWidgets.QCheckBox(self.groupBox)
        self.LEDR4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEDR4.sizePolicy().hasHeightForWidth())
        self.LEDR4.setSizePolicy(sizePolicy)
        self.LEDR4.setText("")
        self.LEDR4.setObjectName("LEDR4")
        self.horizontalLayout_3.addWidget(self.LEDR4)
        self.LEDR3 = QtWidgets.QCheckBox(self.groupBox)
        self.LEDR3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEDR3.sizePolicy().hasHeightForWidth())
        self.LEDR3.setSizePolicy(sizePolicy)
        self.LEDR3.setText("")
        self.LEDR3.setObjectName("LEDR3")
        self.horizontalLayout_3.addWidget(self.LEDR3)
        self.LEDR2 = QtWidgets.QCheckBox(self.groupBox)
        self.LEDR2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEDR2.sizePolicy().hasHeightForWidth())
        self.LEDR2.setSizePolicy(sizePolicy)
        self.LEDR2.setText("")
        self.LEDR2.setObjectName("LEDR2")
        self.horizontalLayout_3.addWidget(self.LEDR2)
        self.LEDR1 = QtWidgets.QCheckBox(self.groupBox)
        self.LEDR1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEDR1.sizePolicy().hasHeightForWidth())
        self.LEDR1.setSizePolicy(sizePolicy)
        self.LEDR1.setText("")
        self.LEDR1.setObjectName("LEDR1")
        self.horizontalLayout_3.addWidget(self.LEDR1)
        self.LEDR0 = QtWidgets.QCheckBox(self.groupBox)
        self.LEDR0.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEDR0.sizePolicy().hasHeightForWidth())
        self.LEDR0.setSizePolicy(sizePolicy)
        self.LEDR0.setText("")
        self.LEDR0.setObjectName("LEDR0")
        self.horizontalLayout_3.addWidget(self.LEDR0)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupChaves = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupChaves.sizePolicy().hasHeightForWidth())
        self.groupChaves.setSizePolicy(sizePolicy)
        self.groupChaves.setObjectName("groupChaves")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupChaves)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SW9 = QtWidgets.QCheckBox(self.groupChaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SW9.sizePolicy().hasHeightForWidth())
        self.SW9.setSizePolicy(sizePolicy)
        self.SW9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SW9.setText("")
        self.SW9.setObjectName("SW9")
        self.horizontalLayout_2.addWidget(self.SW9)
        self.SW8 = QtWidgets.QCheckBox(self.groupChaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SW8.sizePolicy().hasHeightForWidth())
        self.SW8.setSizePolicy(sizePolicy)
        self.SW8.setText("")
        self.SW8.setIconSize(QtCore.QSize(16, 16))
        self.SW8.setObjectName("SW8")
        self.horizontalLayout_2.addWidget(self.SW8)
        self.SW7 = QtWidgets.QCheckBox(self.groupChaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SW7.sizePolicy().hasHeightForWidth())
        self.SW7.setSizePolicy(sizePolicy)
        self.SW7.setText("")
        self.SW7.setObjectName("SW7")
        self.horizontalLayout_2.addWidget(self.SW7)
        self.SW6 = QtWidgets.QCheckBox(self.groupChaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SW6.sizePolicy().hasHeightForWidth())
        self.SW6.setSizePolicy(sizePolicy)
        self.SW6.setText("")
        self.SW6.setObjectName("SW6")
        self.horizontalLayout_2.addWidget(self.SW6)
        self.SW5 = QtWidgets.QCheckBox(self.groupChaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SW5.sizePolicy().hasHeightForWidth())
        self.SW5.setSizePolicy(sizePolicy)
        self.SW5.setText("")
        self.SW5.setObjectName("SW5")
        self.horizontalLayout_2.addWidget(self.SW5)
        self.SW4 = QtWidgets.QCheckBox(self.groupChaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SW4.sizePolicy().hasHeightForWidth())
        self.SW4.setSizePolicy(sizePolicy)
        self.SW4.setText("")
        self.SW4.setObjectName("SW4")
        self.horizontalLayout_2.addWidget(self.SW4)
        self.SW3 = QtWidgets.QCheckBox(self.groupChaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SW3.sizePolicy().hasHeightForWidth())
        self.SW3.setSizePolicy(sizePolicy)
        self.SW3.setText("")
        self.SW3.setObjectName("SW3")
        self.horizontalLayout_2.addWidget(self.SW3)
        self.SW2 = QtWidgets.QCheckBox(self.groupChaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SW2.sizePolicy().hasHeightForWidth())
        self.SW2.setSizePolicy(sizePolicy)
        self.SW2.setText("")
        self.SW2.setObjectName("SW2")
        self.horizontalLayout_2.addWidget(self.SW2)
        self.SW1 = QtWidgets.QCheckBox(self.groupChaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SW1.sizePolicy().hasHeightForWidth())
        self.SW1.setSizePolicy(sizePolicy)
        self.SW1.setText("")
        self.SW1.setObjectName("SW1")
        self.horizontalLayout_2.addWidget(self.SW1)
        self.SW0 = QtWidgets.QCheckBox(self.groupChaves)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SW0.sizePolicy().hasHeightForWidth())
        self.SW0.setSizePolicy(sizePolicy)
        self.SW0.setText("")
        self.SW0.setObjectName("SW0")
        self.horizontalLayout_2.addWidget(self.SW0)
        self.verticalLayout_2.addWidget(self.groupChaves)
        self.groupLCD = QtWidgets.QGroupBox(self.centralwidget)
        self.groupLCD.setMinimumSize(QtCore.QSize(0, 300))
        self.groupLCD.setObjectName("groupLCD")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupLCD)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LCDButton = QtWidgets.QPushButton(self.groupLCD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LCDButton.sizePolicy().hasHeightForWidth())
        self.LCDButton.setSizePolicy(sizePolicy)
        self.LCDButton.setText("")
        self.LCDButton.setFlat(True)
        self.LCDButton.setObjectName("LCDButton")
        self.horizontalLayout_4.addWidget(self.LCDButton)
        self.verticalLayout_2.addWidget(self.groupLCD)
        self.verticalLayout_Reg.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_Reg)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 22))
        self.menubar.setObjectName("menubar")
        self.menuAjuda = QtWidgets.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        self.menuVisualizar = QtWidgets.QMenu(self.menubar)
        self.menuVisualizar.setObjectName("menuVisualizar")
        self.menuROM = QtWidgets.QMenu(self.menuVisualizar)
        self.menuROM.setObjectName("menuROM")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setToolTipsVisible(True)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuAcao = QtWidgets.QMenu(self.menubar)
        self.menuAcao.setObjectName("menuAcao")
        self.menuOpcoes = QtWidgets.QMenu(self.menubar)
        self.menuOpcoes.setObjectName("menuOpcoes")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.actionAssembly = QtWidgets.QAction(MainWindow)
        self.actionAssembly.setObjectName("actionAssembly")
        self.actionROMBinario = QtWidgets.QAction(MainWindow)
        self.actionROMBinario.setCheckable(True)
        self.actionROMBinario.setObjectName("actionROMBinario")
        self.actionROMAssembly = QtWidgets.QAction(MainWindow)
        self.actionROMAssembly.setCheckable(True)
        self.actionROMAssembly.setObjectName("actionROMAssembly")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("theme/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbrir.setIcon(icon)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionNovo = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("theme/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNovo.setIcon(icon1)
        self.actionNovo.setObjectName("actionNovo")
        self.actionProximo = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("theme/go-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProximo.setIcon(icon2)
        self.actionProximo.setObjectName("actionProximo")
        self.actionExecutarFim = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("theme/go-jump.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("theme/go-jump.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExecutarFim.setIcon(icon3)
        self.actionExecutarFim.setObjectName("actionExecutarFim")
        self.actionParar = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("theme/process-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionParar.setIcon(icon4)
        self.actionParar.setObjectName("actionParar")
        self.actionVoltarInicio = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("theme/go-first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVoltarInicio.setIcon(icon5)
        self.actionVoltarInicio.setObjectName("actionVoltarInicio")
        self.actionSalvar_ROM = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("theme/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSalvar_ROM.setIcon(icon6)
        self.actionSalvar_ROM.setObjectName("actionSalvar_ROM")
        self.actionConfiguracoes = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("theme/preferences-system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfiguracoes.setIcon(icon7)
        self.actionConfiguracoes.setObjectName("actionConfiguracoes")
        self.actionEraseRAM = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("theme/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEraseRAM.setIcon(icon8)
        self.actionEraseRAM.setObjectName("actionEraseRAM")
        self.actionIrFim = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("theme/go-last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIrFim.setIcon(icon9)
        self.actionIrFim.setObjectName("actionIrFim")
        self.menuAjuda.addAction(self.actionSobre)
        self.menuROM.addSeparator()
        self.menuROM.addSeparator()
        self.menuROM.addAction(self.actionROMBinario)
        self.menuROM.addAction(self.actionROMAssembly)
        self.menuVisualizar.addAction(self.menuROM.menuAction())
        self.menuArquivo.addAction(self.actionNovo)
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSalvar_ROM)
        self.menuArquivo.addAction(self.actionSair)
        self.menuAcao.addAction(self.actionProximo)
        self.menuAcao.addAction(self.actionExecutarFim)
        self.menuAcao.addAction(self.actionParar)
        self.menuAcao.addAction(self.actionVoltarInicio)
        self.menuOpcoes.addAction(self.actionConfiguracoes)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuAcao.menuAction())
        self.menubar.addAction(self.menuVisualizar.menuAction())
        self.menubar.addAction(self.menuOpcoes.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())
        self.toolBar.addAction(self.actionNovo)
        self.toolBar.addAction(self.actionAbrir)
        self.toolBar.addAction(self.actionSalvar_ROM)
        self.toolBar.addAction(self.actionEraseRAM)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionProximo)
        self.toolBar.addAction(self.actionExecutarFim)
        self.toolBar.addAction(self.actionParar)
        self.toolBar.addAction(self.actionVoltarInicio)
        self.toolBar.addAction(self.actionIrFim)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConfiguracoes)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RESimulatorGUI"))
        self.label_Reg.setText(_translate("MainWindow", "Registradores"))
        self.label_A.setText(_translate("MainWindow", "A"))
        self.label_D.setText(_translate("MainWindow", "D"))
        self.label_S.setText(_translate("MainWindow", "S"))
        self.label_inM.setText(_translate("MainWindow", "inM"))
        self.label_outM.setText(_translate("MainWindow", "outM"))
        self.groupBox.setTitle(_translate("MainWindow", "LEDs"))
        self.LEDR9.setToolTip(_translate("MainWindow", "LEDR9"))
        self.LEDR8.setToolTip(_translate("MainWindow", "LEDR8"))
        self.LEDR7.setToolTip(_translate("MainWindow", "LEDR7"))
        self.LEDR6.setToolTip(_translate("MainWindow", "LEDR6"))
        self.LEDR5.setToolTip(_translate("MainWindow", "LEDR5"))
        self.LEDR4.setToolTip(_translate("MainWindow", "LEDR4"))
        self.LEDR3.setToolTip(_translate("MainWindow", "LEDR3"))
        self.LEDR2.setToolTip(_translate("MainWindow", "LEDR2"))
        self.LEDR1.setToolTip(_translate("MainWindow", "LEDR1"))
        self.LEDR0.setToolTip(_translate("MainWindow", "LEDR0"))
        self.groupChaves.setTitle(_translate("MainWindow", "Chaves"))
        self.SW9.setToolTip(_translate("MainWindow", "SW9"))
        self.SW8.setToolTip(_translate("MainWindow", "SW8"))
        self.SW7.setToolTip(_translate("MainWindow", "SW7"))
        self.SW6.setToolTip(_translate("MainWindow", "SW6"))
        self.SW5.setToolTip(_translate("MainWindow", "SW5"))
        self.SW4.setToolTip(_translate("MainWindow", "SW4"))
        self.SW3.setToolTip(_translate("MainWindow", "SW3"))
        self.SW2.setToolTip(_translate("MainWindow", "SW2"))
        self.SW1.setToolTip(_translate("MainWindow", "SW1"))
        self.SW0.setToolTip(_translate("MainWindow", "SW0"))
        self.groupLCD.setTitle(_translate("MainWindow", "LCD"))
        self.menuAjuda.setTitle(_translate("MainWindow", "A&juda"))
        self.menuVisualizar.setTitle(_translate("MainWindow", "Vis&ualizar"))
        self.menuROM.setTitle(_translate("MainWindow", "&ROM"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Ar&quivo"))
        self.menuAcao.setTitle(_translate("MainWindow", "A&ção"))
        self.menuOpcoes.setTitle(_translate("MainWindow", "Opç&ões"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSobre.setText(_translate("MainWindow", "&Sobre"))
        self.actionAssembly.setText(_translate("MainWindow", "Assembly"))
        self.actionROMBinario.setText(_translate("MainWindow", "&Binário"))
        self.actionROMAssembly.setText(_translate("MainWindow", "&Assembly"))
        self.actionSair.setText(_translate("MainWindow", "Sa&ir"))
        self.actionAbrir.setText(_translate("MainWindow", "&Abrir"))
        self.actionNovo.setText(_translate("MainWindow", "&Novo"))
        self.actionNovo.setToolTip(_translate("MainWindow", "Novo Arquivo"))
        self.actionProximo.setText(_translate("MainWindow", "&Proximo"))
        self.actionProximo.setToolTip(_translate("MainWindow", "Próxima Instrução"))
        self.actionExecutarFim.setText(_translate("MainWindow", "&Executar até o Fim"))
        self.actionExecutarFim.setToolTip(_translate("MainWindow", "Executar até o final"))
        self.actionParar.setText(_translate("MainWindow", "Pa&rar"))
        self.actionParar.setToolTip(_translate("MainWindow", "Parar execução"))
        self.actionVoltarInicio.setText(_translate("MainWindow", "&Voltar ao Início"))
        self.actionVoltarInicio.setToolTip(_translate("MainWindow", "Voltar ao Início"))
        self.actionSalvar_ROM.setText(_translate("MainWindow", "&Salvar ROM"))
        self.actionSalvar_ROM.setToolTip(_translate("MainWindow", "Salvar ROM"))
        self.actionConfiguracoes.setText(_translate("MainWindow", "&Configurações"))
        self.actionConfiguracoes.setToolTip(_translate("MainWindow", "Configurações"))
        self.actionEraseRAM.setText(_translate("MainWindow", "EraseRAM"))
        self.actionEraseRAM.setToolTip(_translate("MainWindow", "Erase RAM"))
        self.actionIrFim.setText(_translate("MainWindow", "Ir para o fim"))
