# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vm_window.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_Rom = QtWidgets.QVBoxLayout()
        self.verticalLayout_Rom.setObjectName("verticalLayout_Rom")
        self.romView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.romView.sizePolicy().hasHeightForWidth())
        self.romView.setSizePolicy(sizePolicy)
        self.romView.setObjectName("romView")
        self.verticalLayout_Rom.addWidget(self.romView)
        self.horizontalLayout.addLayout(self.verticalLayout_Rom)
        self.verticalLayout_Ram = QtWidgets.QVBoxLayout()
        self.verticalLayout_Ram.setObjectName("verticalLayout_Ram")
        self.globalStackView = QtWidgets.QTableView(self.centralwidget)
        self.globalStackView.setObjectName("globalStackView")
        self.verticalLayout_Ram.addWidget(self.globalStackView)
        self.horizontalLayout.addLayout(self.verticalLayout_Ram)
        self.verticalLayout_Reg = QtWidgets.QVBoxLayout()
        self.verticalLayout_Reg.setObjectName("verticalLayout_Reg")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(999999999)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_Reg = QtWidgets.QLabel(self.centralwidget)
        self.label_Reg.setObjectName("label_Reg")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_Reg)
        self.label_SP = QtWidgets.QLabel(self.centralwidget)
        self.label_SP.setObjectName("label_SP")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_SP)
        self.lineEdit_SP = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_SP.setEnabled(False)
        self.lineEdit_SP.setObjectName("lineEdit_SP")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_SP)
        self.label_LCL = QtWidgets.QLabel(self.centralwidget)
        self.label_LCL.setObjectName("label_LCL")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_LCL)
        self.lineEdit_LCL = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_LCL.setEnabled(False)
        self.lineEdit_LCL.setObjectName("lineEdit_LCL")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_LCL)
        self.label_ARG = QtWidgets.QLabel(self.centralwidget)
        self.label_ARG.setObjectName("label_ARG")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_ARG)
        self.lineEdit_ARG = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ARG.setEnabled(False)
        self.lineEdit_ARG.setObjectName("lineEdit_ARG")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ARG)
        self.label_THIS = QtWidgets.QLabel(self.centralwidget)
        self.label_THIS.setObjectName("label_THIS")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_THIS)
        self.lineEdit_THIS = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_THIS.setEnabled(False)
        self.lineEdit_THIS.setObjectName("lineEdit_THIS")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_THIS)
        self.label_THAT = QtWidgets.QLabel(self.centralwidget)
        self.label_THAT.setObjectName("label_THAT")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_THAT)
        self.lineEdit_THAT = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_THAT.setEnabled(False)
        self.lineEdit_THAT.setObjectName("lineEdit_THAT")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_THAT)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.verticalLayout_Reg.addLayout(self.formLayout)
        self.ramView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.ramView.sizePolicy().hasHeightForWidth())
        self.ramView.setSizePolicy(sizePolicy)
        self.ramView.setObjectName("ramView")
        self.verticalLayout_Reg.addWidget(self.ramView)
        self.horizontalLayout.addLayout(self.verticalLayout_Reg)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuAjuda = QtWidgets.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setToolTipsVisible(True)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuAcao = QtWidgets.QMenu(self.menubar)
        self.menuAcao.setObjectName("menuAcao")
        self.menuOpcoes = QtWidgets.QMenu(self.menubar)
        self.menuOpcoes.setObjectName("menuOpcoes")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.actionAssembly = QtWidgets.QAction(MainWindow)
        self.actionAssembly.setObjectName("actionAssembly")
        self.actionROMBinario = QtWidgets.QAction(MainWindow)
        self.actionROMBinario.setCheckable(True)
        self.actionROMBinario.setObjectName("actionROMBinario")
        self.actionROMAssembly = QtWidgets.QAction(MainWindow)
        self.actionROMAssembly.setCheckable(True)
        self.actionROMAssembly.setObjectName("actionROMAssembly")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("theme/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbrir.setIcon(icon)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionNovo = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("theme/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNovo.setIcon(icon1)
        self.actionNovo.setObjectName("actionNovo")
        self.actionProximo = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("theme/go-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProximo.setIcon(icon2)
        self.actionProximo.setObjectName("actionProximo")
        self.actionExecutarFim = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("theme/go-jump.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("theme/go-jump.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExecutarFim.setIcon(icon3)
        self.actionExecutarFim.setObjectName("actionExecutarFim")
        self.actionParar = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("theme/process-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionParar.setIcon(icon4)
        self.actionParar.setObjectName("actionParar")
        self.actionVoltarInicio = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("theme/go-first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVoltarInicio.setIcon(icon5)
        self.actionVoltarInicio.setObjectName("actionVoltarInicio")
        self.actionSalvar_ROM = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("theme/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSalvar_ROM.setIcon(icon6)
        self.actionSalvar_ROM.setObjectName("actionSalvar_ROM")
        self.actionConfiguracoes = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("theme/preferences-system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfiguracoes.setIcon(icon7)
        self.actionConfiguracoes.setObjectName("actionConfiguracoes")
        self.actionEraseRAM = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("theme/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEraseRAM.setIcon(icon8)
        self.actionEraseRAM.setObjectName("actionEraseRAM")
        self.actionIrFim = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("theme/go-last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIrFim.setIcon(icon9)
        self.actionIrFim.setObjectName("actionIrFim")
        self.menuAjuda.addAction(self.actionSobre)
        self.menuArquivo.addAction(self.actionNovo)
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSalvar_ROM)
        self.menuArquivo.addAction(self.actionSair)
        self.menuAcao.addAction(self.actionProximo)
        self.menuAcao.addAction(self.actionExecutarFim)
        self.menuAcao.addAction(self.actionParar)
        self.menuAcao.addAction(self.actionVoltarInicio)
        self.menuOpcoes.addAction(self.actionConfiguracoes)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuAcao.menuAction())
        self.menubar.addAction(self.menuOpcoes.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())
        self.toolBar.addAction(self.actionNovo)
        self.toolBar.addAction(self.actionAbrir)
        self.toolBar.addAction(self.actionSalvar_ROM)
        self.toolBar.addAction(self.actionEraseRAM)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionProximo)
        self.toolBar.addAction(self.actionExecutarFim)
        self.toolBar.addAction(self.actionParar)
        self.toolBar.addAction(self.actionVoltarInicio)
        self.toolBar.addAction(self.actionIrFim)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConfiguracoes)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RESimulatorGUI - VM mode"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Instruções</p></body></html>"))
        self.label_Reg.setText(_translate("MainWindow", "Registradores"))
        self.label_SP.setText(_translate("MainWindow", "SP"))
        self.label_LCL.setText(_translate("MainWindow", "LCL"))
        self.label_ARG.setText(_translate("MainWindow", "ARG"))
        self.label_THIS.setText(_translate("MainWindow", "THIS"))
        self.label_THAT.setText(_translate("MainWindow", "THAT"))
        self.menuAjuda.setTitle(_translate("MainWindow", "A&juda"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Ar&quivo"))
        self.menuAcao.setTitle(_translate("MainWindow", "A&ção"))
        self.menuOpcoes.setTitle(_translate("MainWindow", "Opç&ões"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSobre.setText(_translate("MainWindow", "&Sobre"))
        self.actionAssembly.setText(_translate("MainWindow", "Assembly"))
        self.actionROMBinario.setText(_translate("MainWindow", "&Binário"))
        self.actionROMAssembly.setText(_translate("MainWindow", "&Assembly"))
        self.actionSair.setText(_translate("MainWindow", "Sa&ir"))
        self.actionAbrir.setText(_translate("MainWindow", "&Abrir"))
        self.actionNovo.setText(_translate("MainWindow", "&Novo"))
        self.actionNovo.setToolTip(_translate("MainWindow", "Novo Arquivo"))
        self.actionProximo.setText(_translate("MainWindow", "&Proximo"))
        self.actionProximo.setToolTip(_translate("MainWindow", "Próxima Instrução"))
        self.actionExecutarFim.setText(_translate("MainWindow", "&Executar até o Fim"))
        self.actionExecutarFim.setToolTip(_translate("MainWindow", "Executar até o final"))
        self.actionParar.setText(_translate("MainWindow", "Pa&rar"))
        self.actionParar.setToolTip(_translate("MainWindow", "Parar execução"))
        self.actionVoltarInicio.setText(_translate("MainWindow", "&Voltar ao Início"))
        self.actionVoltarInicio.setToolTip(_translate("MainWindow", "Voltar ao Início"))
        self.actionSalvar_ROM.setText(_translate("MainWindow", "&Salvar VM"))
        self.actionSalvar_ROM.setToolTip(_translate("MainWindow", "Salvar VM"))
        self.actionConfiguracoes.setText(_translate("MainWindow", "&Configurações"))
        self.actionConfiguracoes.setToolTip(_translate("MainWindow", "Configurações"))
        self.actionEraseRAM.setText(_translate("MainWindow", "EraseRAM"))
        self.actionEraseRAM.setToolTip(_translate("MainWindow", "Erase RAM"))
        self.actionIrFim.setText(_translate("MainWindow", "Ir para o fim"))

